version: '3'

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
  db:
    image: mysql
    ports:
      - '3306:3306'
    restart: always
    volumes:
      - ./mysql/mysqldatabase:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'test'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: 3000
      SECRET: 'FEa987fbfGya0jweHGwrg34e5S6ds7'
    container_name: app
    ports:
      - '3000:3000'
    depends_on:
      - 'db'
